# --- File Documentation ---
# This config files define hyperparameters for the model, data and training. 
# You can create multiple config files with different hyperparameters to easily compare different runs. 
# --------------------------


model:
  model_name: TwoHiddenLayerMLP   # Can be TwoHiddenLayerMLP, OneHiddenLayerMLP or TwoLayerCNN 
  hidden_size_mlp: 32             # Number of neurons in the hidden layer for MLP models.
  # CNN only
  input_channels: 1               # Number of input variables. We only have 1 in the file we are using.
  n_kernels_cnn: 8                # Number of kernels (convolutional filters)in the convolutional layer for CNN models.
  n_channels_input_cnn: 1         # Number of channels in the input data for CNN models. For example, if you have 3 input variables, this should be set to 3.

data:
  data_in_name: lowres_era5_features.nc                 # Predictor input path: either one NetCDF file or a folder of per-variable NetCDF files.
  data_target_name: chirps-v2.0.1DD.1981-2025.nc # Name of the target data file.
  data_path: /Data/gfi/users/rogui7909/data/AfricaPrecip/ # Path to the directory containing the data files.  
  batch_size: 128                                         # Batch size for training and validation.
  transform_X: StandardScalerX                            # Transformation to apply to the input data. Can be None or a class in src.data.transforms. 
  transform_y: None                                       # Transformation to apply to the target data. Can be None or a class in src.data.transforms.        

trainer:
  max_epochs: 20          # Number of epochs to train the model.
  learning_rate: 0.0001   # Learning rate for the optimizer.
  accelerator: gpu        # Accelerator to use for training. Can be 'cpu', 'gpu', or other things.  
  devices: 1              # Number of devices to use for training. For example, if you have 2 GPUs and want to use both, set this to 2.

logging:
  project: african-rainfall-tests   # Name of the Weights & Biases project to log the training runs to.
  run_name: baseline        # Name of the Weights & Biases run. You can use this to differentiate between different runs in the same project.
  base_dir: outputs         # Base directory to save the model checkpoints and logs. Weights & Biases will also save the logs in their own cloud storage, but this is useful to have a local copy as well.
